name: Publish Release

on:
  push:
    tags:
      - "*"

jobs:
  create_release:
    name: Create Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create XCFramework
        uses: unsignedapps/swift-create-xcframework@v2.3.0
      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GH_PAT }}"
          prerelease: false
          files: |
            TPObfuscation.sha256
            TPObfuscation.zip
